package main

import (
	_ "github.com/Pavel-Casp/MyGoProject1/docs" // docs is generated by Swag CLI
	"github.com/Pavel-Casp/MyGoProject1/internal/handler"
	"github.com/Pavel-Casp/MyGoProject1/internal/service"
	"github.com/Pavel-Casp/MyGoProject1/internal/storage"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger" // echo-swagger middleware
)

// @title Calculator API
// @version 1.0
// @description This is a simple calculator API with token-based authentication
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	// Инициализация
	store := storage.NewMemoryStorage()
	calcService := service.NewCalculatorService(store)
	calcHandler := handler.NewCalculatorHandler(calcService)

	e := echo.New()
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Роуты
	e.GET("/token", calcHandler.GenerateToken)
	e.POST("/sum", calcHandler.HandleSum)
	e.POST("/multiply", calcHandler.HandleMultiply)
	e.GET("/results/:key", calcHandler.GetResult)
	e.DELETE("/clear", calcHandler.ClearData)

	// Swagger route
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.Logger.Fatal(e.Start(":8080"))
}
